# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build Vue
on: 
  push:
    branches: [ master ]
  workflow_run:
    workflows: [Build Vue]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.0
      with:
        username: 'andrewGIS'
        reponame: 'mchs_map'
        token: ${{ secrets.GITHUB_TOKEN }}
      env:
        VUE_APP_PUBLIC_PATH: '/mchs_map'
